
const KENYA_COUNTIES = [
  { code: '001', name: 'Mombasa', capital: 'Mombasa City', towns: ['Nyali', 'Kisauni', 'Likoni', 'Changamwe', 'Jomvu'] },
  { code: '002', name: 'Kwale', capital: 'Kwale', towns: ['Ukunda', 'Diani', 'Msambweni', 'Lungalunga'] },
  { code: '003', name: 'Kilifi', capital: 'Kilifi', towns: ['Malindi', 'Watamu', 'Mariakani', 'Kaloleni'] },
  { code: '004', name: 'Tana River', capital: 'Hola', towns: ['Garsen', 'Bura', 'Madogo'] },
  { code: '005', name: 'Lamu', capital: 'Lamu', towns: ['Mokowe', 'Faza', 'Mpeketoni'] },
  { code: '006', name: 'Taita Taveta', capital: 'Wundanyi', towns: ['Voi', 'Taveta', 'Mwatate', 'Wundanyi'] },
  { code: '007', name: 'Garissa', capital: 'Garissa', towns: ['Dadaab', 'Hagadera', 'Ijara'] },
  { code: '008', name: 'Wajir', capital: 'Wajir', towns: ['Habaswein', 'Tarbaj', 'Buthale'] },
  { code: '009', name: 'Mandera', capital: 'Mandera', towns: ['Rhamu', 'Takaba', 'Elwak'] },
  { code: '010', name: 'Marsabit', capital: 'Marsabit', towns: ['Moyale', 'Laisamis', 'Sololo'] },
  { code: '011', name: 'Isiolo', capital: 'Isiolo', towns: ['Garbatulla', 'Merti', 'Kinna'] },
  { code: '012', name: 'Meru', capital: 'Meru', towns: ['Maua', 'Nkubu', 'Timau', 'Laare'] },
  { code: '013', name: 'Tharaka-Nithi', capital: 'Chuka', towns: ['Chogoria', 'Marimanti', 'Chiakariga'] },
  { code: '014', name: 'Embu', capital: 'Embu', towns: ['Runyenjes', 'Siakago', 'Manyatta'] },
  { code: '015', name: 'Kitui', capital: 'Kitui', towns: ['Mwingi', 'Mutomo', 'Ikutha', 'Kabati'] },
  { code: '016', name: 'Machakos', capital: 'Machakos', towns: ['Athi River', 'Mlolongo', 'Kangundo', 'Tala', 'Matuu'] },
  { code: '017', name: 'Makueni', capital: 'Wote', towns: ['Mtito Andei', 'Emali', 'Kibwezi', 'Makindu'] },
  { code: '018', name: 'Nyandarua', capital: 'Ol Kalou', towns: ['Ndaragwa', 'Engineer', 'Miharati'] },
  { code: '019', name: 'Nyeri', capital: 'Nyeri', towns: ['Karatina', 'Othaya', 'Mukurweini', 'Mweiga'] },
  { code: '020', name: 'Kirinyaga', capital: 'Kerugoya', towns: ['Kutus', 'Sagana', 'Wanguru', 'Baricho'] },
  { code: '021', name: "Murang'a", capital: "Murang'a", towns: ['Kangema', 'Kigumo', 'Maragua', 'Kandara'] },
  { code: '022', name: 'Kiambu', capital: 'Kiambu', towns: ['Thika', 'Ruiru', 'Kikuyu', 'Limuru', 'Kabete', 'Juja'] },
  { code: '023', name: 'Turkana', capital: 'Lodwar', towns: ['Kakuma', 'Lokichoggio', 'Lokitaung'] },
  { code: '024', name: 'West Pokot', capital: 'Kapenguria', towns: ['Kacheliba', 'Sigor', 'Chepareria'] },
  { code: '025', name: 'Samburu', capital: 'Maralal', towns: ['Baragoi', 'Wamba', 'Archers Post'] },
  { code: '026', name: 'Trans Nzoia', capital: 'Kitale', towns: ['Endebess', 'Kiminini', 'Saboti'] },
  { code: '027', name: 'Uasin Gishu', capital: 'Eldoret', towns: ['Burnt Forest', 'Turbo', 'Moiben', 'Ziwa'] },
  { code: '028', name: 'Elgeyo-Marakwet', capital: 'Iten', towns: ['Kapsowar', 'Chebara', 'Tambach'] },
  { code: '029', name: 'Nandi', capital: 'Kapsabet', towns: ['Nandi Hills', 'Mosoriot', 'Kabiyet', 'Kaptumo'] },
  { code: '030', name: 'Baringo', capital: 'Kabarnet', towns: ['Eldama Ravine', 'Marigat', 'Mogotio', 'Kabartonjo'] },
  { code: '031', name: 'Laikipia', capital: 'Rumuruti', towns: ['Nanyuki', 'Nyahururu', 'Doldol'] },
  { code: '032', name: 'Nakuru', capital: 'Nakuru', towns: ['Naivasha', 'Gilgil', 'Molo', 'Njoro', 'Mau Narok'] },
  { code: '033', name: 'Narok', capital: 'Narok', towns: ['Kilgoris', 'Lolgorian', 'Suswa', "Ololulung'a"] },
  { code: '034', name: 'Kajiado', capital: 'Kajiado', towns: ['Ngong', 'Ongata Rongai', 'Kitengela', 'Isinya', 'Loitokitok'] },
  { code: '035', name: 'Kericho', capital: 'Kericho', towns: ['Litein', 'Londiani', 'Kipkelion', 'Sosiot'] },
  { code: '036', name: 'Bomet', capital: 'Bomet', towns: ['Sotik', 'Chepalungu', 'Konoin', 'Longisa'] },
  { code: '037', name: 'Kakamega', capital: 'Kakamega', towns: ['Mumias', 'Butere', 'Lugari', 'Malava', 'Shinyalu'] },
  { code: '038', name: 'Vihiga', capital: 'Mbale', towns: ['Chavakali', 'Hamisi', 'Luanda', 'Emuhaya'] },
  { code: '039', name: 'Bungoma', capital: 'Bungoma', towns: ['Webuye', 'Kimilili', 'Sirisia', 'Malakisi'] },
  { code: '040', name: 'Busia', capital: 'Busia', towns: ['Malaba', 'Nambale', 'Funyula', 'Butula'] },
  { code: '041', name: 'Siaya', capital: 'Siaya', towns: ['Bondo', 'Ugunja', 'Yala', 'Ukwala'] },
  { code: '042', name: 'Kisumu', capital: 'Kisumu', towns: ['Muhoroni', 'Ahero', 'Maseno', 'Kombewa'] },
  { code: '043', name: 'Homa Bay', capital: 'Homa Bay', towns: ['Oyugis', 'Mbita', 'Kendu Bay', 'Rangwe'] },
  { code: '044', name: 'Migori', capital: 'Migori', towns: ['Rongo', 'Awendo', 'Uriri', 'Suna'] },
  { code: '045', name: 'Kisii', capital: 'Kisii', towns: ['Ogembo', 'Keroka', 'Suneka', 'Marani'] },
  { code: '046', name: 'Nyamira', capital: 'Nyamira', towns: ['Manga', 'Nyansiongo', 'Ekerenyo'] },
  { code: '047', name: 'Nairobi', capital: 'Nairobi City', towns: ['Westlands', 'Kibera', 'Eastleigh', 'Karen', 'Ruaraka', 'Kasarani', 'Langata', 'Dagoretti', 'Embakasi', 'Kamukunji', 'Makadara', 'Mathare', 'Njiru', 'Starehe'] }
]

module.exports = KENYA_COUNTIES